font_family      monospace
font_size 10.0

# OS Window Close#
confirm_os_window_close 0

map ctrl+c copy_to_clipboard
map ctrl+v pas
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

dynamic_background_opacity yes
background_opacity 0.7
background_blur 10

# BEGIN_KITTY_THEME
# Adapta Nokto Maia
include current-theme.conf
# END_KITTY_THEME
